### ISSUE TITLE
opens and closes

### ISSUE THREAD

**Issue by huglester** [mardukbp/activatewindow#1]
Hello

I see this error:

```
activatewindow.exe
>  (55/55 choices)
﻿010 - Google Chro
Settings - Sound - Google Chrome
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:395:23
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mardukbp** [comment]
That is a bug in [heatseeker](https://github.com/rschmitt/heatseeker/blob/master/src/main.rs#L395), the program that filters the list of open windows. I will investigate it soon and open an issue there.

I plan to rewrite activatewindow using Tcl/Tk. Then this problem will be avoided at all :)

**Comment by mardukbp** [comment]
@huglester Somehow, as I was about to report the issue the author of heatseeker fixed it. I have updated activatewindow with the latest version of heatseeker. Please try it and let me know if it does not crash anymore to close this issue. If it does crash please do the following in cmd.exe:

```batch
set RUST_BACKTRACE=full
activatewindow
```

and paste the trace here.

**Comment by huglester** [comment]
maybe you got built binary?

**Comment by mardukbp** [comment]
If you mean the binary of activatewindow, please download the latest release.

Am 31. Januar 2021 09:40:03 MEZ schrieb Jaroslav Petrusevic <notifications@github.com>:
>maybe you got built binary?

**Comment by huglester** [comment]
Hello I think it works!!!
any idea if I make "auto full screen" feature to be off?

**Comment by mardukbp** [comment]
I am glad it works now :)

Not sure what you mean with auto full screen. If you double click activatewindow you should get a small window. As stated in the README you can pin it to the taskbar to use the Windows key and a number to launch it.

**Comment by mardukbp** [comment]
@huglester Check out the newest release v0.4. Now Explorer windows are included and windows from background processes are not. If something does not work, please open an issue.

**Comment by huglester** [comment]
thanks. now when I pick window from the list, it does not resize it. perfect thanks

**Comment by mardukbp** [comment]
Yeah, I also fixed that and only today I realized that is what you meant. Sorry.

**Comment by huglester** [comment]
all good! thanks for help

**Comment by mardukbp** [comment]
@huglester I just released a new version that includes all windows with the same name (previously only one of them was shown). They are distinguished using a counter. At the moment I cannot think of other shortcoming that needs to be addressed. If you find something that needs to be fixed, please open an issue.
